name: build

on:
  push:
    branches-ignore:
    - main
    - release/*
    - dependabot/**
    tags-ignore:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true

    - name: Setup Pkl
      id: setup_pkl
      env:
        PKL_VERSION: 0.30.2
      shell: bash
      run: |-
        set -u
        DIR="$(mktemp -d /tmp/pkl-${PKL_VERSION}-XXXXXX)"
        PKL="${DIR}/pkl"
        PKL_DOWNLOAD_URL="https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-linux-amd64"
        curl -sfL -o "${PKL}" "${PKL_DOWNLOAD_URL}"
        chmod +x "${PKL}"
        echo "${DIR}" >> "${GITHUB_PATH}"
        echo "PKL=${PKL}" >> "${GITHUB_OUTPUT}"
  
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        PKL: ${{ steps.setup_pkl.outputs.PKL }}
